#!/usr/bin/env python3
"""Compress robot photos into <photos_dir>/N.jpg and write photos.js.

Usage: python tools/compress_photos.py <src_dir> <photos_dir> <out_js>
A real photo filename has at least two dots, e.g.
'24. Unitree [X] 2025 CN.png' or '127..png'.
Single-dot names like '1.jpg' are group covers and are skipped.
"""
import os
import re
import sys
from PIL import Image

PAT = re.compile(r'^(\d+)\..*\.\w+$')
MAX = 1200
QUALITY = 82


def main():
    src, photos_dir, out_js = sys.argv[1], sys.argv[2], sys.argv[3]
    os.makedirs(photos_dir, exist_ok=True)
    by_no = {}
    for root, _dirs, files in os.walk(src):
        for name in files:
            m = PAT.match(name)
            if m:
                by_no[int(m.group(1))] = os.path.join(root, name)
    nums = sorted(by_no)
    for no in nums:
        img = Image.open(by_no[no]).convert('RGB')
        img.thumbnail((MAX, MAX))
        img.save(os.path.join(photos_dir, '%d.jpg' % no), 'JPEG',
                 quality=QUALITY, optimize=True)
    with open(out_js, 'w', encoding='utf-8') as f:
        f.write('/* Generated by tools/compress_photos.py. Do not edit by hand. */\n')
        f.write('(function (global) {\n  "use strict";\n  const PHOTO_LIST = [\n')
        for no in nums:
            f.write('    "%d.jpg",\n' % no)
        f.write('  ];\n')
        f.write('  if (typeof module !== "undefined" && module.exports) module.exports = PHOTO_LIST;\n')
        f.write('  global.PHOTO_LIST = PHOTO_LIST;\n')
        f.write('})(typeof window !== "undefined" ? window : this);\n')
    print('wrote', len(nums), 'photos; range', nums[0], '-', nums[-1])


if __name__ == '__main__':
    main()
