#!/usr/bin/env python3
"""Generate data/robots.js from the source xlsx.

Usage: python tools/gen_robots.py <xlsx> <out_js>
Sheet1 columns: seq | brand | model | year | country | url
"""
import sys
import json
import openpyxl


def main():
    xlsx, out_js = sys.argv[1], sys.argv[2]
    wb = openpyxl.load_workbook(xlsx, data_only=True)
    ws = wb['Sheet1']
    robots = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        seq = row[0]
        if seq is None:
            continue
        robots.append({
            'no': str(int(seq)),
            'brand': (row[1] or '').strip(),
            'model': (row[2] or '').strip(),
            'year': int(row[3]) if row[3] is not None else None,
            'country': (row[4] or '').strip(),
        })
    body = json.dumps(robots, ensure_ascii=False, indent=2)
    js = (
        '/* Generated by tools/gen_robots.py. Do not edit by hand. */\n'
        '(function (global) {\n'
        '  "use strict";\n'
        '  const ROBOTS = ' + body + ';\n'
        '  if (typeof module !== "undefined" && module.exports) module.exports = ROBOTS;\n'
        '  global.ROBOTS = ROBOTS;\n'
        '})(typeof window !== "undefined" ? window : this);\n'
    )
    with open(out_js, 'w', encoding='utf-8') as f:
        f.write(js)
    print('wrote', len(robots), 'robots to', out_js)


if __name__ == '__main__':
    main()
